version: '3.11'
services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:80"  # Map the container's port 80 to your host's port 3000

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"  # Map the container's port 5000 to your host's port 5000
    environment:
      FLASK_APP: app.py  # Change app.py to your main Flask file if different